import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // libsSidebar: [
  //   { 
  //     type: 'category',
  //     label: 'Documentation Notes',
  //     collapsible: true,
  //     collapsed: false,
  //     link: {
  //       type: 'generated-index',
  //       title: 'Docusaurus Guides',
  //       description: 'Learn about the most important Docusaurus concepts!',
  //       // slug: '/category/docusaurus-guides',
  //       keywords: ['guides'],
  //       image: '/img/docusaurus.png',
  //     },
  //     items: [
  //     ]
  //   }
  // ],
  // summarySidebar: [
  //   { 
  //     type: 'category',
  //     label: 'Documentation Notes',
  //     collapsible: true,
  //     collapsed: false,
  //     link: {
  //       type: 'generated-index',
  //       title: 'Docusaurus Guides',
  //       description: 'Learn about the most important Docusaurus concepts!',
  //       // slug: '/category/docusaurus-guides',
  //       keywords: ['guides'],
  //       image: '/img/docusaurus.png',
  //     },
  //     items: [
  //       'summary/summary-docs',
  //       'summary/blog',
  //       {
  //         type: 'link',
  //         label: 'Facebook', // The link label
  //         href: 'https://facebook.com', // The external URL
  //       },
  //     ]
  //   },
  // ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
